### ISSUE TITLE
Wrong Chatbot link on afterflood.in

### ISSUE THREAD

**Issue by leo424y** [afterflood/afterflood.in#18]
should be 
https://www.messenger.com/t/afterflood.in
works

not

https://www.messenger.com/t/keralarescue.in
which doesn't okr

<img width="456" alt="screen shot 2018-09-14 at 11 50 17 am" src="https://user-images.githubusercontent.com/1384394/45528757-63eaf780-b814-11e8-8537-13e77e035579.png">

**Comment by bodhish** [comment]
@leo424y Fixed. Thanks for informing. 👍
