### ISSUE TITLE
Responsive design issues in Mobile

### ISSUE THREAD

**Issue by arunelias** [afterflood/afterflood.in#7]
Page renders with design issues in Mobile browsers.
Please add custom CSS options in the Gitbook.
![afterflood_firefox](https://user-images.githubusercontent.com/32271975/44502988-a86df200-a6b1-11e8-8ef0-f5291cd9fec5.jpeg)

Browser: Firefox nightly

**Comment by bodhish** [comment]
Can you update it @arunelias.
Open for PR

**Comment by rejuls** [comment]
Could not reproduce

**Comment by bodhish** [comment]
Closing this as it looks like a browser issue.
